version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    expose:
      - 9000

  web:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge